### ISSUE TITLE
Onboarding pSB1C3 and "flanking" of insert sequences

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#105]
With TWIST delivering a newly synthesized pSB1C3, we will soon be ready to go through the onboarding process. This can take some time, but a crucial decisions will be where to declare the insertion points for newly synthesized products. We can have multiple and for features that we want to add, those can be added (flanked) to the insertion sequence.

Examples:
**MCSless pSB1C3**, where insertion begins before the traditional BioBrick prefix and suffix. 
- Inserts, like previous Interlab devices, would get synthesized with the complete BioBrick prefix and suffix.
- Type IIS parts would get synthesized with BsaI and fusion sites (This would become a new Type IIS backbone)

**pSB1C3**, insertion begins within BioBrick prefix and suffix

Considerations
- Extra bases! Helps when we need padding, hurts when we are hitting against the limit.
- Same as above, but this may help or hurt synthesizability (example, GC content of NotI site in BioBrick prefix and suffix)

**Comment by jakebeal** [comment]
I don't have a position on which option is preferred, but whichever it is, I'd like to get some examples of it and write a test so that we can validate that everything in the distribution build plan (https://github.com/iGEM-Engineering/iGEM-distribution/blob/develop/distribution.gb) is compliant and report errors in the [README_distribution.md](https://github.com/iGEM-Engineering/iGEM-distribution/blob/develop/README_distribution.md) file.

With respect to adding flanking sequences: I'd suggest this is a good use of the "Composites" tab.  Right now we're mostly just saying "put these parts in this backbone", but we can also readily say, "flank these parts with these Level 0 GoldenGate sequences and put them in the backbone"

**Comment by vinoo-igem** [comment]
Just a quick follow-up, I put together a draft order to see if there would be any issue with synthesizing these Interlab 2018 devices with and without the BioBrick prefix and suffix, and there were no issues from TWIST's automated validation (BBa_R0040 does pose an issue due to size)

BBa_R0040
BBa_I20270
BBa_J364000
BBa_J364001
BBa_J364002
BBa_J364007
BBa_J364008
BBa_J364009

**Comment by vinoo-igem** [comment]
We're sending off pSB1C3 for onboarding. Once the process is started, I should work on a bit of documentation for it. But for now...

pSB1CX

It has two insertion sites

1. **3_BBprefix-suffix**: '3' to denote that this will result in a sequence correct pSB1C3 with the full BioBrick prefix and suffix. Ideal for Interlab devices. Note that this is not for CDS parts which has a shorter prefix.
2. **MCS-less**: Ideal for when we want to include flanking sequences to aid in assembly (Type IIS) or add extra bases to hit synthesis minimums

**Comment by vinoo-igem** [comment]
pSB1C3 has been onboarded!
