### ISSUE TITLE
Add "Getting started" page to read-the-docs

### ISSUE THREAD

**Issue by noahsprent** [iGEM-Engineering/iGEM-distribution#160]
With a more in-depth guide to getting started vs READ.me, as we look to get more people involved. Please suggest here in the discussion what should be included :)

- What the purpose of the distribution is
- Focused on what we are looking for help with
    - Contributors: How to contribute a package
    - Reviewers: How to review a package
    - Commentors: How to help by commenting
    - Users: How to use the distribution

**Comment by noahsprent** [comment]
Oh we should probably also include on the page:
- Documentors: How to write documentation and what we need ;)

**Comment by jakebeal** [comment]
While it needs to be expanded and updated, a good starting place would be the current project README

**Comment by GC-repeat** [comment]
Documentation on how to contribute packages to the distribution. The "safe/newbie" way : fork, branch, pull request and the "you know what you're doing" way : branch, pull request.

**Comment by jakebeal** [comment]
Building on @GC-repeat 's suggestion, a good starting place may be the slides from last year: https://docs.google.com/presentation/d/1M8Y0O0K6hVmj5Z9A3so9j7jQadq0JPLm/edit?usp=sharing&ouid=100312901663678842419&rtpof=true&sd=true

**Comment by traci-igem** [comment]
I think part of the "getting started" from my perspective would need to include some really basic introduction to how to navigate through the GitHub for folks who have never touched the platform before. 

For example: Explain what "Issues" are used for and how to engage on them. It was challenging for me to first understand the basic navigation of GitHub, since I would not have gone to "Issues" for discussions, etc. It doesn't need to be anything long, but literally a sentence or so explaining the different tabs would be really helpful.

**Comment by noahsprent** [comment]
Based on discussion on Slack, a detailed tutorial on how to fill out the excel sheets would be very helpful.

**Comment by noahsprent** [comment]
Thanks everyone for freedback! I've created a project ['Documentation' here](https://github.com/orgs/iGEM-Engineering/projects/1/views/1). And split the things discussed here out in to separate issues with the tag 'documentation'. From now on if you have any suggestions for additions to the docs please add them as an individual issue and tag them with 'documentation'.
