### ISSUE TITLE
Create CRISPR-Cas collection

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#23]
Explore the parts/devices needed for starting a collection, and also the possible patent issues.

**Comment by GC-repeat** [comment]
What are we thinking about here ? Cas9, dCas9, Cas12,.... different sgRNA scaffold,... ? all the above ?

**Comment by jakebeal** [comment]
Could potentially be any of them --- I think that teams will at least want Cas9 and dCas9.  What would you propose?

**Comment by GC-repeat** [comment]
I would include Cas9 and dCas9 for sure and I think Cas13a and Cas12a could be good picks. Cas13a has been used by other teams since it's successful entry in 2017 as a diagnosis tool based on the SHERLOCK paper. Cas12a is interesting as it can be used for diagnosis (EPFL iGEM 2018 and [Li et al, 2018, _Cell Discov._](https://www.nature.com/articles/s41421-018-0028-z) for example) or as a replacement for Cas9 when the NGG PAM sequence is an issue for example. Also, from what I've seen it can be useful for the [plant folks](https://www.frontiersin.org/articles/10.3389/fpls.2020.00264/full)?
A scaffold for the guide for each system should be in the collection too. I don't know if the teams use the same or different ones.
Maybe some effectors if some are more used than others could be added too to go with the dead Cas.

**Comment by jakebeal** [comment]
@GC-repeat Want to identify some specific sequences to be included?

**Comment by GC-repeat** [comment]
Sure, I can do that.

**Comment by jakebeal** [comment]
Here's another good paper that has actual units on its E. coli dCas9 gates!  https://www.embopress.org/doi/full/10.15252/msb.20209618
