### ISSUE TITLE
Possible issue with duplicate names or identities from builds into fasta

### ISSUE THREAD

**Issue by vinoo-igem** [iGEM-Engineering/iGEM-distribution#241]
I didn't have a chance to look into this indepth, but I believe there's an issue with the above. I noticed this in the small molecules package. The package states there's 37 things being built, and the build sheet reflects that, but I believe the fasta only has 35 things from that package.

I think this is because there is C0080, C0040 with part names of AraC, TetR that may be overwritten or not written into the fasta because of other AraC and TetR. The sequences for these same named parts are different.

**Comment by jakebeal** [comment]
It looks like it's not an issue of duplicate names, but something getting disconnected instead. I find this in the build log:
```
Part cannot be synthesized, sequence is missing: https://github.com/iGEM-Engineering/iGEM-distribution/Plastic%20Degradation/PETase_library_ins_BBa_K2010999
Part cannot be synthesized, sequence is missing: https://github.com/iGEM-Engineering/iGEM-distribution/Small%20Molecule%20Inducers/Coding_sequences_ins_BBa_C0040
Part cannot be synthesized, sequence is missing: https://github.com/iGEM-Engineering/iGEM-distribution/Small%20Molecule%20Inducers/Coding_sequences_ins_BBa_C0080
```

However, the distribution file does have the sequence in there... this requires deeper investigation... why fail on this but not the others near-identical to it?

**Comment by jakebeal** [comment]
Found the problem. These were some of the first parts we imported, and their import was subject to a conversion bug that has since been fixed, which left them with the wrong type, such that they didn't look like DNA components and thus couldn't have their sequences computed as part of a flanked insert. The cached versions were still there, however, so they were never re-imported and converted correctly. 

This should thus be fixed simply by removing the cached copies and allowing them to reconvert.
