### ISSUE TITLE
Change "Basic Parts" to "Parts/Devices"

### ISSUE THREAD

**Issue by jakebeal** [iGEM-Engineering/iGEM-distribution#8]
The "Basic Parts" tab is being used for things that iGEM doesn't call "Basic Parts", so we should change the name.

This will be a multi-part refactor:
 - The existing spreadsheets need to have the tab name changed.
 - The automation needs to be updated to look for the new tab name
 - README should be updated

**Comment by vignoni** [comment]
Still don't know how we land on the #4  : 

> Don't we want to make **all the composite parts** from parts (even if we want to add the composite one)?

**Comment by jakebeal** [comment]
I am not convinced that we do want to make all the composite parts from parts.  If there is a well-established composite part, then I believe it's equivalent directly use the composite (which identifies its subparts in its description) or to recreate the composite.  In this case, there are more opportunities for making a mistake with recreating than with linking.

**Comment by vinoo-igem** [comment]
The way I've been conceptualizing the tabs is roughly:

Parts -> Identifiers with documentation tied to a DNA sequence (whether on the iGEM Registry, GenBank, or in the doc)
Libraries + Composites -> How we want samples of those DNA sequences to be built through synthesis

To expand on Jake's point: not allowing composite parts within the Parts tab means that a documented device must include the way it was built (scars b/w subparts). And, we may lose out on the easy identification of common devices. Ex, "lets synthesize the Repressilator" is easier to communicate, and for us to keep track of the exact sequence to synthesize.

I wonder if this is just one of the challenges of abstraction vs build process. Maybe, part of the validation in the future includes checks for all parts and lists out their subparts including their scars/if any.

**Comment by vignoni** [comment]
Maybe I did not explain myself properly. I agree with @jakebeal comment:

> I am not convinced that we do want to make all the composite parts from parts. If there is a well-established composite part, then I believe it's equivalent to directly use the composite (which identifies its subparts in its description) or recreate the composite. In this case, there are more opportunities for making a mistake with recreating than with linking.

I never meant not to allow composite parts in the parts tab, as (in general)  I advocate to tie down a part (both basic and composite in igem's language) with its DNA sequence instance because up to this point we all know that sequence matters and in particular in the RBS+CDS connecting region.

Regarding this:
>To expand on Jake's point: not allowing composite parts within the Parts tab means that a documented device must include the way it was built (scars b/w subparts). And, we may lose out on the easy identification of common devices. Ex, "lets synthesize the Repressilator" is easier to communicate, and for us to keep track of the exact sequence to synthesize.

and related to my previous comment, I think that we are not yet at the point where the functionality of a device is build-independent. If we lose this, it will be a problem for the further characterization of parts.

However, in the event of let say de novo creation of composite parts from parts I believe, it does make sense to do it within the framework @jakebeal set up with the excel sheet + python + SBOL, but now I see that this is a different story (more in line with the EC orders than with the distribution). 

In any case, and sorry for repeating myself, I think it's important by all means to keep the relationship between a sequence and the element/part/composite in the repository/distribution.

**Comment by vinoo-igem** [comment]
Ah! I did misunderstand, thanks for clarifying! I agree on both of these points:

> we are not yet at the point where the functionality of a device is build-independent. If we lose this, it will be a problem for the further characterization of parts.

> in the event of let say de novo creation of composite parts from parts I believe, it does make sense to do it within the framework @jakebeal set up with the excel sheet + python + SBOL
